### ISSUE TITLE
`Conn.Stat().Extra` and `Stream.Stat().Extra` are nil. Cannot assign values.

### ISSUE THREAD

**Issue by lthibault** [libp2p/go-libp2p-net#33]
It is currently impossible to assign values to the `Extra` map from within a `net.Notifiee` method.  Indeed, in e.g. `Notifiee.Connected()`, `conn.Stat().Extra` is `nil`.

It would be nice to have an initialized map, here, as it allows library users to pass around contextual information.  An alternative might be to extend https://github.com/libp2p/go-libp2p-net/issues/32 to support a `WithContext()` method similar to `http.Request`.  This would allow users to bind contextual data to connections/streams via `context.Context`, which feels a bit more idiomatic.

Thoughts?

**Comment by Stebalien** [comment]
So, `Stat` was designed to expose read-only status information from the underlying transport. Updating it externally doesn't really make sense (and doing this atomically would be tricky).

However, I agree that a way to associate data with streams and connections would be nice (it actually just came up here: https://github.com/libp2p/go-libp2p/issues/475#issuecomment-436915163).

**Comment by lthibault** [comment]
Makes sense.  Feel free to close this.
