### ISSUE TITLE
conn.RemotePeer() returning the wrong peer ID with a circuit relay

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p-net#45]
Imagine we just dialed a peer with the multiaddress of `/ip4/127.0.0.1/tcp/5002/p2p/QmdPU7PfRyKehdrP5A3WqmjyD6bhVpU1mLGKppa2FjGDjZ/p2p-circuit/p2p/QmVT6GYwjeeAF5TR485Yc58S3xRF5EFsZ5YAF4VcP3URHt`

```go
h.Network().Notify(&inet.NotifyBundle{
    ConnectedF: func(net inet.Network, conn inet.Conn) {
      // Must be handled in a goroutine as this callback cannot be blocking.
      go func() {

        s, err := h.NewStream(
          context.Background(),
          conn.RemotePeer(), // QmdPU7PfRyKehdrP5A3WqmjyD6bhVpU1mLGKppa2FjGDjZ
          handshakeProtocol,
        )
     ...
     ...
   }()
 })
```

`conn.RemotePeer()` returns the peer ID of the circuit/relay node (`QmdPU7PfRyKehdrP5A3WqmjyD6bhVpU1mLGKppa2FjGDjZ`), not the specific peer (`QmVT6GYwjeeAF5TR485Yc58S3xRF5EFsZ5YAF4VcP3URHt`). As a result, the stream is with the wrong peer. 

I can't figure out where the implementation of the [Conn](https://github.com/libp2p/go-libp2p-net/blob/master/interface.go#L94) interface is so I have no idea where to start investigating this further.

Additionally, it would be nice if `conn.NewStream(procotol)` worked. It would be intuitive to call this when I want to open/use a stream with the remote peer.

**Comment by prestonvanloon** [comment]
If there was some way to understand that this Connected event was the connection to the relay/circuit node, I would just ignore this event. That would solve my problem as well, I suppose.

**Comment by Stebalien** [comment]
> If there was some way to understand that this Connected event was the connection to the relay/circuit node, I would just ignore this event.

This is exactly what's happening (unless there's a hidden bug here I'm not seeing). Libp2p will fire events for _all_ connections, including the implicit one to the relay.

If you'd just like to create a new stream to the remote peer, you shouldn't need to use notifications. Instead, call `NewStream` directly:

```go
h.Peerstore().AddAddr(targetPeerID, targetMultiaddr)
stream, err := h.NewStream(ctx, targetPeerID, "/some/protocol")
```

This will automatically create any necessary connections and then create a new stream to the target peer.

**Comment by prestonvanloon** [comment]
My use case is that I need to exchange some additional information to determine when two peers are compatible. 

The problem is that a relay node doesn’t speak the same protocols that I expect my peer to speak and I want to disconnect anyone that doesn’t support this protocol.

How can I determine that this Connected event is for a relay hop when dialing the peer that I want?

**Comment by prestonvanloon** [comment]
Could the PeerConnected event solve my problem? Or would it still fire when the relay node is connected?

https://github.com/libp2p/go-libp2p-net/blob/master/interface.go#L222

**Comment by Stebalien** [comment]
> Could the PeerConnected event solve my problem? Or would it still fire when the relay node is connected?

It would if it were implemented.

> How can I determine that this Connected event is for a relay hop when dialing the peer that I want?

Unfortunately, you can't. Connections aren't dedicated to any single purpose. It's entirely possible to get weird situations like:

1. DHT dials peer R when trying to connect to find peer P.
2. As a result of this query, we learn that peer P is using peer R as a relay.
3. We connect to peer P through peer R.

However, you could create something like the [connection manager](https://github.com/libp2p/go-libp2p-connmgr) (or just fork it) that closes all connections older than some grace period that aren't being used by the relay service (you can check the potocols for each stream in `conn.Streams()`) or your application.
